# Generated by Django 3.1.7 on 2021-03-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAluno', models.CharField(max_length=255)),
                ('emailAluno', models.CharField(max_length=255)),
                ('senhaAluno', models.CharField(max_length=255)),
                ('avatarAluno', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProfessor', models.CharField(max_length=255)),
                ('emailProfessor', models.CharField(max_length=255)),
                ('senhaProfessor', models.CharField(max_length=255)),
                ('avatarProfessor', models.CharField(max_length=255)),
            ],
        ),
    ]
