# Generated by Django 3.1.7 on 2021-03-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0002_auto_20210327_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='professorAluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registers.professor'),
            preserve_default=False,
        ),
    ]
