# Generated by Django 3.1.7 on 2021-03-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0003_aluno_professoraluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='avatarProfessor',
            field=models.FileField(upload_to='media/%Y/%m/%d/'),
        ),
    ]
