# Generated by Django 3.1.7 on 2021-03-28 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0005_auto_20210328_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cursoAluno',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
