# Generated by Django 3.1.7 on 2021-03-28 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0006_auto_20210328_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCurso', models.CharField(max_length=255)),
                ('variosAtributosCurso', models.CharField(max_length=255)),
                ('quantidadeAulasCurso', models.CharField(max_length=255)),
                ('professorCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.professor')),
            ],
        ),
    ]
