# Generated by Django 3.1.7 on 2021-04-09 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0009_curso_categoriacurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cursoAluno',
        ),
        migrations.AddField(
            model_name='aluno',
            name='cursoAluno',
            field=models.ManyToManyField(to='registers.Curso'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTurma', models.CharField(max_length=255)),
                ('cursoTurma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.curso')),
            ],
        ),
    ]
