# Generated by Django 3.1.7 on 2021-04-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0010_auto_20210409_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='cursoAluno',
            new_name='cursosAluno',
        ),
    ]
