# Generated by Django 3.1.7 on 2021-04-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0011_auto_20210409_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='cursosAluno',
        ),
        migrations.AddField(
            model_name='aluno',
            name='turmasAluno',
            field=models.ManyToManyField(to='registers.Turma'),
        ),
    ]
