# Generated by Django 3.1.7 on 2021-04-16 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0012_auto_20210409_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAbreviadoAula', models.CharField(max_length=255)),
                ('nomeCompletoAula', models.CharField(max_length=255)),
                ('textoAula', models.CharField(max_length=255)),
                ('textoAdicionalAula', models.CharField(max_length=255)),
                ('cursoAula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.curso')),
            ],
        ),
    ]
