# Generated by Django 3.1.7 on 2021-04-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0013_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='cursoAula',
        ),
        migrations.AddField(
            model_name='curso',
            name='aulaCurso',
            field=models.ManyToManyField(to='registers.Aula'),
        ),
    ]
