# Generated by Django 3.1.7 on 2021-04-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0014_auto_20210425_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagemCurso',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/curso/%Y/%m/%d/'),
        ),
    ]
