# Generated by Django 3.1.7 on 2021-05-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0015_curso_imagemcurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='nomeTurma',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
