# Generated by Django 3.1.7 on 2021-06-10 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0016_turma_nometurma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagemChat', models.CharField(max_length=255)),
                ('dataMensagemChat', models.DateTimeField(editable=False)),
                ('alunoChat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.aluno')),
                ('turmaChat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.turma')),
            ],
        ),
    ]
