# Generated by Django 3.1.7 on 2021-06-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0017_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='dataMensagemChat',
        ),
    ]
