# Generated by Django 3.1.7 on 2021-09-11 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0022_auto_20210911_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='turmaRoom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registers.turma'),
        ),
    ]
