# Generated by Django 3.1.7 on 2022-05-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0023_room_turmaroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='linkAula',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
