# Generated by Django 3.1.7 on 2022-05-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0024_aula_linkaula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=1000000)),
                ('respostaA', models.CharField(max_length=1000000)),
                ('respostaB', models.CharField(max_length=1000000)),
                ('respostaC', models.CharField(max_length=1000000)),
                ('respostaD', models.CharField(max_length=1000000)),
            ],
        ),
    ]
