# Generated by Django 3.1.7 on 2022-05-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0025_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='pergunta',
            field=models.CharField(default=1, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='respostaA',
            field=models.CharField(default=1, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='respostaB',
            field=models.CharField(default=1, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='respostaC',
            field=models.CharField(default=1, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='respostaD',
            field=models.CharField(default=1, max_length=1000000),
            preserve_default=False,
        ),
    ]
